---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(ggridges)
library(plotly)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "SNWD", "TMIN", "TMAX"), 
    date_min = "2020-01-01",
    date_max = "2020-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
   replace_na(list(prcp = 0, snwd = 0, tmax = 0, tmin = 0)) %>% 
  select(name, id, everything())
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
weather_df %>% 
  mutate(
    temp_range = str_c("Temp Max: degree C ", tmax, "\nTemp Min: degree C ", tmin)
  ) %>% 
  plot_ly(
    x = ~date, y = ~prcp, type = "scatter", mode = "markers",
    color = ~name, text = ~temp_range, alpha = .8
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
weather_df %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    month = recode(month, 
             "1" = "January", "2" = "February",
             "3" = "March", "4" = "April",
             "5" = "May", "6" = "June",
             "7" = "July", "8" = "August",
             "9" = "September", "10" = "October",
             "11" = "November", "12" = "December")
  ) %>% 
  mutate(
    month = factor(month)
  ) %>% 
  mutate(
    month = fct_reorder(month, tmax)
  ) %>% 
  plot_ly(
    y = ~tmax, color = ~month, type = "box", colors = "viridis"
  )
```

### Chart C

```{r}
weather_df %>% 
  plot_ly(
    x = ~date, y = ~prcp
  ) %>%  
  add_lines(color = ~name, color = "viridis", alpha = 0.8)
```

Here's back to the [index](index.html) page.