---
title: "NOAA data description"
output: 
  html_document:
    toc: true
    toc_float: true
---

# This page is the short description of the NOAA National Climatic Data


The Global Historical Climatology Network daily (GHCNd) is an integrated database of daily climate summaries from land surface stations across the globe. GHCNd is made up of daily climate records from numerous sources that have been integrated and subjected to a common suite of quality assurance reviews.

GHCNd contains records from more than 100,000 stations in 180 countries and territories. NCEI provides numerous daily variables, including maximum and minimum temperature, total daily precipitation, snowfall, and snow depth. About half the stations only report precipitation. Both record length and period of record vary by station and cover intervals ranging from less than a year to more than 175 years.
Here is the link for [GHCNd](https://www.ncei.noaa.gov/products/land-based-station/global-historical-climatology-network-daily)

You can download the climate Data here:
[climate data](https://www.ncdc.noaa.gov/cdo-web/search?datasetid=GHCND)


 




